- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
      project_id: [my-project]
      auth_kind: serviceaccount
      service_account_file: /home/[account_name]/my_account.json
      scopes:
        - www.googleapis.com/auth/compute
      zone: "asia-northeast1"
      region: "asia-northeast1-c"

  tasks:
    - name: Create an instance
      local_action:
        module: gce
        instance_names: "ansible-test"
        machine_type: "f1-micro"
        image: "ubuntu-1604-lts"
        zone: "{{ zone }}"
        service_account_email: ""
        #pem_file: "{{ pem_file }}"
        project_id: "{{ project_id }}"
        disk_size: 64
